spring.application.name=University


spring.datasource.url=jdbc:postgresql://ep-autumn-feather-ae9w2sbm-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JFiLgoBe9uG7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




# Application logging
logging.level.root=INFO
logging.level.com.nilesh.University=INFO

# Hibernate SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE